ユーザ検索を追加
NaCl-Ltd/intern-2023-B pull request #36
Opened 2023-09-01 07:02 UTC by kondo-117

Close #13
 
### 実装したこと
- ユーザ一覧にユーザ検索を実装した
- 主にindex.html.erbファイルに`turbo_frame`を用いて`@users`の値を取得するようにした
- cssにて検索ボタンのデザインを追加した

2023-09-01 07:16 UTC, hosogimiho approved these changes
問題ないと思います。

2023-09-01 10:07 UTC, tufusa requested changes
> 検索をかけて、出てきたユーザの名前をクリックしても遷移しない

turbo frameの仕様だと思うのですが、該当の`link_to`の`target`属性に`_self`を指定したところ遷移させることができました。ユーザ体験的にはリロードが挟まらないhttps://github.com/NaCl-Ltd/intern-2023-B/pull/36/commits/781d8bd79516400974c99de2e2e4cef56695e347 の状態の方が良いと思うので、検討をお願いします。

2023-09-04 05:11 UTC, TakuyaNoguchi commented on app/controllers/users_controller.rb
> +              .where('name LIKE ?', "%#{params[:search_users]}%")
インターンシップお疲れ様です、NaClの野口です。

チームAのPRにコメントした内容にこちらのコードも該当しそうです。こちら確認してみてください。

https://github.com/NaCl-Ltd/intern-2023-A/pull/44#discussion_r1314440550

2023-09-05 12:15 UTC, kondo-117 commented
お待たせしました、ご指摘いただいたことを直しました。

2023-09-06 01:48 UTC, tufusa approved these changes
LGTM！

2023-09-06 01:48 UTC, merged